version: '3.8'

services:
  pgvector:
    image: pgvector/pgvector:pg17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=vectors
      - POSTGRES_USER=pgvector
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgvector -d vectors"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgvector_data: 